git:
    depth: 1
language: python
install:
    - pip install . codecov
script:
    - coverage run -m pytest
matrix:
  include:
    - python: nightly
      dist: xenial
      sudo: true
after_success:
    - codecov
